# Generated by Django 4.2.5 on 2023-11-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_transportationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='TransportationType',
            field=models.CharField(blank=True, choices=[('PUJ', 'PUJ'), ('Modernized PUJ', 'Modernized PUJ'), ('AirConditioned PUJ', 'AirConditioned PUJ'), ('Regular PUJ', 'Regular PUJ'), ('Modernized Bus', 'Modernized Bus')], default='PUJ', max_length=100, null=True),
        ),
    ]
