# Generated by Django 4.2 on 2023-09-04 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published'], 'verbose_name_plural': 'Article'},
        ),
    ]
