# Generated by Django 4.2.5 on 2023-10-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_transpotype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentprice',
            name='CurrentFareBus',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='currentprice',
            name='CurrentSucceedingBus',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
