# Generated by Django 4.2.5 on 2023-09-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_alter_article_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleSeries',
        ),
    ]
