# Generated by Django 4.2.5 on 2023-11-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_currentprice_currentfarebus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionID', models.CharField(blank=True, max_length=20, null=True)),
                ('DateIn', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
