# Generated by Django 4.2.5 on 2023-09-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Website', '0003_delete_article_delete_articleseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocName', models.CharField(max_length=200)),
                ('Coordinates', models.CharField(max_length=100)),
            ],
        ),
    ]
