# Generated by Django 4.2.5 on 2023-09-21 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_routes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Routes',
            new_name='Route',
        ),
    ]
