# Generated by Django 4.2.5 on 2023-09-21 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_rename_routes_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.route'),
        ),
        migrations.AlterField(
            model_name='location',
            name='Coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='LocName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='Rname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
