# Generated by Django 4.2.5 on 2023-10-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_location_route_alter_location_coordinates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCrawl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrawlDate', models.CharField(blank=True, max_length=200, null=True)),
                ('CrawlPHP', models.IntegerField(blank=True, null=True)),
                ('CrawlUSD', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
