# Generated by Django 4.2.5 on 2023-11-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_transportationrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportationrecord',
            old_name='latitude',
            new_name='latitudeIN',
        ),
        migrations.RenameField(
            model_name='transportationrecord',
            old_name='longitude',
            new_name='latitudeOUT',
        ),
        migrations.AddField(
            model_name='transportationrecord',
            name='longitudeIN',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportationrecord',
            name='longitudeOUT',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
