# Generated by Django 4.2.5 on 2023-11-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0010_transportationrecordout_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransportationRecordOUT',
        ),
        migrations.AddField(
            model_name='transportationrecord',
            name='latitudeOUT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportationrecord',
            name='longitudeOUT',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
