# Generated by Django 4.2.5 on 2023-11-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0012_transportationrecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportationrecord',
            name='user',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
