# Generated by Django 4.2.5 on 2023-11-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0015_transportationrecord_km'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
