# Generated by Django 4.2.5 on 2023-11-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0017_rename_user_transportationrecord_conductorsn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportationrecord',
            old_name='conductorSN',
            new_name='user',
        ),
    ]
