# Generated by Django 4.2.5 on 2023-11-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0018_rename_conductorsn_transportationrecord_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportationrecord',
            name='commuterSN',
        ),
    ]
