# Generated by Django 4.2.5 on 2023-11-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0019_remove_transportationrecord_commutersn'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationrecord',
            name='commuterStatus',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
