# Generated by Django 4.2.5 on 2023-11-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0020_transportationrecord_commuterstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportationrecord',
            name='commuterStatus',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
