# Generated by Django 4.2.5 on 2023-11-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0022_transportationrecord_transpotype'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationrecord',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
