# Generated by Django 4.2.5 on 2023-10-09 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrentDate', models.DateField(blank=True, null=True)),
                ('CurrentFare', models.FloatField(blank=True, default=0, null=True)),
                ('CurrentDiesel', models.FloatField(blank=True, default=0, null=True)),
                ('CurrentSucceeding', models.FloatField(blank=True, default=0, null=True)),
                ('Num', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataCrawl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrawlDate', models.CharField(blank=True, max_length=200, null=True)),
                ('CrawlPHP', models.FloatField(blank=True, null=True)),
                ('CrawlUSD', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rname', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocName', models.CharField(blank=True, max_length=200, null=True)),
                ('Coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.route')),
            ],
        ),
    ]
