# Generated by Django 4.2.5 on 2023-11-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_cashiertransaction_cashin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('scan_type', models.CharField(blank=True, max_length=20, null=True)),
                ('extracted_data', models.TextField(blank=True, null=True)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('TranspoSN', models.CharField(blank=True, max_length=25, null=True, unique=True)),
            ],
        ),
    ]
