# Generated by Django 4.2.5 on 2023-11-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0013_alter_transportationrecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationrecord',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
