# Generated by Django 4.2.5 on 2023-11-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0014_transportationrecord_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationrecord',
            name='km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
