# Generated by Django 4.2.5 on 2023-10-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='validation',
        ),
    ]
