# Generated by Django 4.2 on 2023-09-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_firstname_customuser_graduation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='firstName',
            new_name='middle_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='middleName',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='surname',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='graduation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
