# Generated by Django 4.2 on 2023-09-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_firstname_customuser_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='validID',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
