# Generated by Django 4.2.5 on 2023-09-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_validid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='QR',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='validID',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
