# Generated by Django 4.2.5 on 2023-09-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_contactnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contactNumber',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='emergencyContact',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
