# Generated by Django 4.2.5 on 2023-09-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_contactnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='UserGroup',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
