# Generated by Django 4.2.5 on 2023-09-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_usergroup_customuser_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='UserGroup',
            field=models.CharField(blank=True, choices=[('Cashier', 'Cashier'), ('Conductor', 'Conductor'), ('Employer', 'Employer'), ('Commuter', 'Commuter')], max_length=100, null=True),
        ),
    ]
