# Generated by Django 4.2.5 on 2023-09-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customuser_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='UserGroup',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
